// Single source of truth for deploy-time URLs used across the site.
// Override SITE_URL for a custom domain by building with
//   VITE_SITE_URL=https://your.domain npm run build
// (and set the matching Vite `base` via BASE_PATH — see vite.config.js).

export const REPO = 'https://github.com/Aninda7479/AgentApp'

// Where the promo site itself is served from. On GitHub Pages project sites
// this is https://<user>.github.io/<repo>; for a custom domain set VITE_SITE_URL.
export const SITE_URL =
  (import.meta.env && import.meta.env.VITE_SITE_URL) ||
  'https://aninda7479.github.io/AgentApp'

// Current published version — keep in sync with the package versions.
// This is automatically updated by scripts/bump-version.js.
export const VERSION = '0.41.0'

// Raw install-script endpoints (served from website/public/).
export const INSTALL_SH = `${SITE_URL}/install.sh`
export const INSTALL_PS1 = `${SITE_URL}/install.ps1`

// Latest GitHub release (used as a fallback / "all downloads" link).
export const RELEASES_LATEST = `${REPO}/releases/latest`

// Deterministic desktop installer asset URLs.
// Names are generated by Tauri from the `productName` field in tauri.conf.json.
// Pattern: {productName}_{version}_{target}.{ext}
export const DL = {
  win:       `${REPO}/releases/latest/download/SuperAgent_${VERSION}_x64-setup.exe`,
  winMsi:    `${REPO}/releases/latest/download/SuperAgent_${VERSION}_x64_en-US.msi`,
  mac:       `${REPO}/releases/latest/download/SuperAgent_${VERSION}_aarch64.dmg`,
  macIntel:  `${REPO}/releases/latest/download/SuperAgent_${VERSION}_x64.dmg`,
  linux:     `${REPO}/releases/latest/download/SuperAgent_${VERSION}_amd64.AppImage`,
  deb:       `${REPO}/releases/latest/download/SuperAgent_${VERSION}_amd64.deb`,
}

// Server / HomeLab / CLI standalone archive download URLs (for terminal & CLI --serve mode)
export const SERVER_DL = {
  linux:    `${REPO}/releases/latest/download/superagent-cli-v${VERSION}-linux-x64.tar.gz`,
  linuxArm: `${REPO}/releases/latest/download/superagent-cli-v${VERSION}-linux-arm64.tar.gz`,
  windows:  `${REPO}/releases/latest/download/superagent-cli-v${VERSION}-windows-x64.zip`,
  mac:      `${REPO}/releases/latest/download/superagent-cli-v${VERSION}-macos-arm64.zip`,
  macIntel: `${REPO}/releases/latest/download/superagent-cli-v${VERSION}-macos-x64.zip`,
}

// Browser extension release package (.zip)
export const EXTENSION_DL = `${REPO}/releases/latest/download/superagent-browser-extension-v${VERSION}.zip`

