import { PCBGraph } from './types';

/**
 * KiCad 8/9 S-Expression Schematic Exporter (.kicad_sch)
 */
export function exportToKiCad(graph: PCBGraph): { schematic: string; project: string } {
  const timestamp = Math.floor(Date.now() / 1000);
  const uuid = (prefix: string) => `${prefix}-${Math.random().toString(36).substring(2, 10)}`;

  let sch = `(kicad_sch (version 20231120) (generator "SuperAgent_PCB_Engine") (generator_version "1.0")
  (uuid "${uuid('root')}")
  (paper "A4")
  (title_block
    (title "${graph.metadata.name}")
    (date "${graph.metadata.updated}")
    (rev "${graph.metadata.revision}")
    (company "${graph.metadata.author}")
  )
  (lib_symbols
`;

  // Define Symbols
  graph.components.forEach((comp) => {
    sch += `    (symbol "${comp.id}_Sym" (pin_names (offset 1.016)) (in_bom yes) (on_board yes)
      (property "Reference" "${comp.id}" (at 0 5.08 0))
      (property "Value" "${comp.value || comp.name}" (at 0 -5.08 0))
      (property "Footprint" "${comp.package}" (at 0 -7.62 0) (hide yes))
      (property "MPN" "${comp.mpn}" (at 0 -10.16 0) (hide yes))
      (property "LCSC" "${comp.lcscPart || ''}" (at 0 -12.7 0) (hide yes))
      (symbol "${comp.id}_Sym_1_1"
`;
    comp.pins.forEach((pin, idx) => {
      const yOffset = idx * -2.54;
      sch += `        (pin ${pin.type === 'power_in' ? 'power_in' : 'bidirectional'} line (at -5.08 ${yOffset.toFixed(2)} 0) (length 2.54)
          (name "${pin.name}" (effects (font (size 1.27 1.27))))
          (number "${pin.number}" (effects (font (size 1.27 1.27))))
        )
`;
    });
    sch += `      )
    )
`;
  });

  sch += `  )
  (sheet_instances
    (path "/" (page "1"))
  )
`;

  // Instantiate Symbols on Sheet
  graph.components.forEach((comp, idx) => {
    const posX = comp.x ? (comp.x * 0.25).toFixed(2) : (50 + (idx % 3) * 60).toFixed(2);
    const posY = comp.y ? (comp.y * 0.25).toFixed(2) : (50 + Math.floor(idx / 3) * 50).toFixed(2);
    sch += `  (symbol (lib_id "${comp.id}_Sym") (at ${posX} ${posY} 0) (unit 1)
    (uuid "${uuid(comp.id.toLowerCase())}")
    (property "Reference" "${comp.id}" (at ${posX} ${(parseFloat(posY) - 5).toFixed(2)} 0))
    (property "Value" "${comp.value || comp.name}" (at ${posX} ${(parseFloat(posY) + 5).toFixed(2)} 0))
  )
`;
  });

  // Export Global Net Labels
  graph.nets.forEach((net, idx) => {
    const netX = (180 + (idx % 4) * 25).toFixed(2);
    const netY = (40 + Math.floor(idx / 4) * 15).toFixed(2);
    sch += `  (global_label "${net.name}" (shape input) (at ${netX} ${netY} 0)
    (effects (font (size 1.27 1.27)))
    (uuid "${uuid('label')}")
    (property "IntersheetRefs" "${net.connections.map((c) => `${c.componentId}.${c.pinNumber}`).join(', ')}")
  )
`;
  });

  sch += `)\n`;

  const project = JSON.stringify(
    {
      meta: {
        filename: `${graph.metadata.projectId}.kicad_pro`,
        version: 1,
      },
      net_settings: {
        classes: [
          {
            name: 'Default',
            clearance: 0.2,
            trace_width: 0.25,
            via_dia: 0.6,
            via_drill: 0.3,
          },
          {
            name: 'Power',
            clearance: 0.3,
            trace_width: 0.5,
            nets: graph.nets.filter((n) => n.netClass === 'power' || n.netClass === 'ground').map((n) => n.name),
          },
        ],
      },
      schematic: {
        annotate_start_num: 1,
        drawing: {
          dashed_lines_dash_length_ratio: 12.0,
          dashed_lines_gap_length_ratio: 3.0,
        },
      },
    },
    null,
    2
  );

  return { schematic: sch, project };
}

/**
 * Altium Designer Protel 2 Netlist Exporter (.NET)
 */
export function exportToAltiumNetlist(graph: PCBGraph): string {
  let output = `[
PROTEL ADVANCED PCB NETLIST 2.0
PROJECT: ${graph.metadata.name}
REVISION: ${graph.metadata.revision}
DATE: ${graph.metadata.updated}
]
`;

  // Components Section
  graph.components.forEach((comp) => {
    output += `(
${comp.id}
${comp.package}
${comp.value || comp.name}
${comp.description || ''}
${comp.mpn}
)
`;
  });

  // Nets Section
  graph.nets.forEach((net) => {
    output += `(
${net.name}
`;
    net.connections.forEach((conn) => {
      output += `${conn.componentId}-${conn.pinNumber}
`;
    });
    output += `)
`;
  });

  return output;
}

/**
 * SKiDL (Python-based Schematic Synthesis) Exporter
 */
export function exportToSKiDL(graph: PCBGraph): string {
  let py = `#!/usr/bin/env python3
"""
SKiDL Schematic Synthesis Script
Project: ${graph.metadata.name} (${graph.metadata.revision})
Generated by: SuperAgent AI PCB Workspace
"""

from skidl import *

# Initialize Circuit
set_default_tool(KICAD8)

# 1. Define Components
`;

  graph.components.forEach((comp) => {
    py += `${comp.id.toLowerCase()} = Part(
    lib='Device',
    name='${comp.id.startsWith('R') ? 'R' : comp.id.startsWith('C') ? 'C' : 'IC'}',
    footprint='${comp.package}',
    value='${comp.value || comp.name}',
    ref='${comp.id}'
)
${comp.id.toLowerCase()}.fields['MPN'] = '${comp.mpn}'
${comp.id.toLowerCase()}.fields['LCSC'] = '${comp.lcscPart || ''}'

`;
  });

  py += `# 2. Define Nets\n`;
  graph.nets.forEach((net) => {
    const netVar = net.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
    py += `net_${netVar} = Net('${net.name}')\n`;
  });

  py += `\n# 3. Interconnect Components & Nets\n`;
  graph.nets.forEach((net) => {
    const netVar = net.name.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
    const pinTargets = net.connections.map((c) => `${c.componentId.toLowerCase()}['${c.pinNumber}']`).join(' += ');
    if (pinTargets) {
      py += `net_${netVar} += ${pinTargets}\n`;
    }
  });

  py += `\n# 4. Generate Output Netlist & ERC
ERC()
generate_netlist(file_='${graph.metadata.projectId}.net')
`;

  return py;
}

/**
 * EasyEDA Pro Schematic JSON Exporter
 */
export function exportToEasyEDA(graph: PCBGraph): string {
  const easyEdaData = {
    head: {
      docType: '5',
      editorVersion: '2.1.0',
      c_para: {
        name: graph.metadata.name,
        revision: graph.metadata.revision,
        author: graph.metadata.author,
      },
    },
    canvas: 'CA~1000~1000~#FFFFFF~yes~#080808~10~1000~1000~line~0.5~0~none',
    components: graph.components.map((c, i) => ({
      itemType: 1,
      head: { c_para: { package: c.package, value: c.value || c.name, mpn: c.mpn, lcsc: c.lcscPart || '' } },
      x: c.x || 100 + (i % 4) * 150,
      y: c.y || 100 + Math.floor(i / 4) * 120,
      rotation: 0,
      designator: c.id,
      pins: c.pins.map((p) => ({ num: p.number, name: p.name, type: p.type })),
    })),
    nets: graph.nets.map((n) => ({
      name: n.name,
      netClass: n.netClass,
      nodes: n.connections.map((conn) => `${conn.componentId}.${conn.pinNumber}`),
    })),
  };

  return JSON.stringify(easyEdaData, null, 2);
}

/**
 * Bill of Materials (BOM) Exporter (CSV Format for JLCPCB / LCSC / DigiKey)
 */
export function exportToBOM(graph: PCBGraph): string {
  let csv = `Designator,Quantity,Name,Value,Package,Manufacturer,MPN,LCSC Part #,Description\n`;

  // Group by MPN/Value
  const groups = new Map<string, { comp: typeof graph.components[0]; designators: string[] }>();

  graph.components.forEach((comp) => {
    const key = `${comp.mpn}__${comp.value || ''}__${comp.package}`;
    if (!groups.has(key)) {
      groups.set(key, { comp, designators: [comp.id] });
    } else {
      groups.get(key)!.designators.push(comp.id);
    }
  });

  groups.forEach(({ comp, designators }) => {
    const desList = `"${designators.join(', ')}"`;
    const line = [
      desList,
      designators.length,
      `"${comp.name}"`,
      `"${comp.value || ''}"`,
      `"${comp.package}"`,
      `"${comp.manufacturer}"`,
      `"${comp.mpn}"`,
      `"${comp.lcscPart || ''}"`,
      `"${comp.description.replace(/"/g, '""')}"`,
    ].join(',');
    csv += line + '\n';
  });

  return csv;
}
