/**
 * Canonical on-disk storage types for conversations, chats, and projects.
 *
 * Chat transcripts are stored as JSON arrays of {@link StoredChatMessage} in
 * `chat.json`. Per-chat session state lives in a separate `config.json`
 * matching {@link ChatConfig}. Project-level configuration uses
 * {@link ProjectConfig}.
 */

/** A single step in a conversation trajectory (user message, assistant reply, tool call, etc.). */
export interface TrajectoryStep {
  id: string;
  type: 'user' | 'assistant' | 'tool_call' | 'tool_result' | 'thought';
  content: string;
  timestamp?: string;
  status?: 'pending' | 'running' | 'success' | 'error';
  toolName?: string;
  metadata?: {
    filename?: string;
    originalCode?: string;
    modifiedCode?: string;
    mediaType?: 'image' | 'pdf' | 'ppt' | 'audio';
    addedLines?: number;
    removedLines?: number;
    filesExplored?: number;
    foldersExplored?: number;
    workedDuration?: string;
    [key: string]: any;
  };
}

/** A configured AI provider with API credentials. */
export interface StoredProvider {
  id: string;
  name: string;
  type: 'env' | 'key' | 'custom';
  apiKey: string;
  baseUrl: string;
}

/** An AI model entry in the models catalog. */
export interface StoredModel {
  id: string;
  name: string;
  providerId: string;
  enabled: boolean;
  description?: string;
  contextLimit?: string;
  outputLimit?: string;
  inputModalities?: string[];
  outputModalities?: string[];
  pricing?: { inputPer1M?: string; outputPer1M?: string; cachedInputPer1M?: string };
  caching?: boolean;
  type?: string;
}

// ---------------------------------------------------------------------------
// New storage schema types (replacing StoredChat / StoredChatConfig / StoredProject)
// ---------------------------------------------------------------------------

/** Content payload for a user-authored message. */
export interface UserContent {
  prompt: string;
}

/** A single step inside an AI response (tool call, reasoning, reply, files). */
export interface AIStep {
  toolcall?: any;
  thought?: string;
  reply?: string;
  files?: string[];
}

/** Content payload for an AI-authored message. */
export interface AIContent {
  steps: AIStep[];
}

/**
 * A single message in a chat conversation, persisted in `chat.json`.
 * The file is a JSON array of these objects.
 */
export interface StoredChatMessage {
  id: string;
  type: 'user' | 'AI';
  /** ISO 8601 timestamp — when the message started being generated. */
  timestart: string;
  /** ISO 8601 timestamp — when the message finished. */
  timeend: string;
  /** Model identifier that produced this message. */
  model: string;
  content: UserContent | AIContent;
}

/**
 * Per-chat configuration persisted in `config.json` alongside the chat
 * directory. Keeps session/memory state separate from the transcript.
 */
export interface ChatConfig {
  'chat-id': string;
  /** Title generated by the model for this conversation. */
  title: string;
  /** Associated project id, or null for standalone chats. */
  'project-id': string | null;
  /** Agent memory / context for this chat. */
  memory: string;
  /** Tools the agent may invoke in this chat. */
  'allowed-tools': string[];
  /** Whether the agent may reach the network. */
  'internet-access': boolean;
  /** Shell command prefixes the agent may execute. */
  'allowed-terminal-commands': string[];
  /** Permission mode: `allow` = auto-approve, `ask` = require confirmation, `none` = no tools. */
  'permission-mode': 'allow' | 'ask' | 'none';
  /** Whether the chat runs inside a sandbox. */
  sandbox: boolean;
}

/**
 * Project-level configuration persisted in `config.json` under the project
 * directory.
 */
export interface ProjectConfig {
  name: string;
  /** Folders the user has added to this project. */
  'given-folders': string[];
  /** Shell command prefixes allowed in this project. */
  'allowed-commands': string[];
  /** Compacted project memory. */
  memory: string;
  /** Long-form memory with full detail and intent. */
  'detailed-memory': string;
  /** Whether the agent may access the network in this project. */
  'network-access': boolean;
}

// ---------------------------------------------------------------------------
// Legacy type aliases — kept for backward compat during migration
// ---------------------------------------------------------------------------

/** @deprecated Use {@link ChatConfig} instead. */
export type StoredChatConfig = Partial<ChatConfig> & {
  model?: string;
  provider?: string;
  baseUrl?: string;
  contextWindow?: number;
  memory?: string;
  contextSummary?: string;
  updatedAt?: string;
};

/** @deprecated Use {@link ProjectConfig} instead. */
export type StoredProject = {
  name: string;
  folders: string[];
  allowedCommands?: string[];
  storageKey?: string;
};

/** @deprecated Use {@link StoredChatMessage}[] (array in `chat.json`) instead. */
export interface StoredChat {
  id: string;
  title: string;
  project: string;
  model: string;
  timestamp: string;
  steps: any[];
  projectStorageKey?: string;
  isRunning?: boolean;
  startedAt?: number;
  lastError?: string;
  provider?: string;
  baseUrl?: string;
  contextWindow?: number;
  memory?: string;
  contextSummary?: string;
}

/** Keys that belong in `chat.json` (transcript data). */
export const CHAT_FILE_KEYS = [
  'id',
  'title',
  'project',
  'timestamp',
  'steps',
  'projectStorageKey',
  'isRunning',
  'startedAt',
  'lastError'
] as const;

/** Keys that belong in `config.json` (session / memory state). */
export const CHAT_CONFIG_KEYS = [
  'model',
  'provider',
  'baseUrl',
  'contextWindow',
  'memory',
  'contextSummary',
  'updatedAt'
] as const;

/** Top-level shape of all persisted conversation store data. */
export interface StoreData {
  connectedProviders: StoredProvider[];
  modelsCatalog: StoredModel[];
  projects?: StoredProject[];
  chats?: StoredChat[];
}

/** Root directory paths for the conversation storage filesystem layout. */
export interface ConversationRoots {
  userDataDir: string;
  baseDir: string;
  projectsDir: string;
  chatsDir: string;
}
