import { exec } from 'child_process';
import { promisify } from 'util';
import * as path from 'path';
import * as fs from 'fs';

const execAsync = promisify(exec);

export interface MouseCoordinates {
  x: number;
  y: number;
}

export class ComputerUse {
  /**
   * Captures a PNG screenshot of the primary display and saves it to the specified file path.
   * If no path is provided, it saves to a temp file in the project directory.
   */
  public static async takeScreenshot(outputPath?: string): Promise<string> {
    const targetPath = outputPath || path.join(process.cwd(), `screenshot-${Date.now()}.png`);
    
    // Windows Forms + Drawing GDI+ screen capture script
    const psScript = `Add-Type -AssemblyName System.Windows.Forms, System.Drawing; [System.Windows.Forms.Screen]::PrimaryScreen.Bounds | %{ $bmp = New-Object System.Drawing.Bitmap $_.Width, $_.Height; $g = [System.Drawing.Graphics]::FromImage($bmp); $g.CopyFromScreen($_.X, $_.Y, 0, 0, $bmp.Size); $bmp.Save('${targetPath.replace(/'/g, "''")}', [System.Drawing.Imaging.ImageFormat]::Png); $g.Dispose(); $bmp.Dispose(); }`;
    const cmd = `powershell -NoProfile -ExecutionPolicy Bypass -Command "${psScript}"`;

    try {
      await execAsync(cmd);
      if (fs.existsSync(targetPath)) {
        return targetPath;
      }
      throw new Error('Screenshot file was not generated by PowerShell.');
    } catch (err: unknown) {
      throw new Error(`Failed to capture screenshot: ${(err as Error).message}`);
    }
  }

  /**
   * Moves the cursor to the specified coordinates (X, Y) relative to the screen.
   */
  public static async moveMouse(x: number, y: number): Promise<string> {
    const psScript = `Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Cursor]::Position = New-Object System.Drawing.Point(${x}, ${y})`;
    const cmd = `powershell -NoProfile -ExecutionPolicy Bypass -Command "${psScript}"`;

    try {
      await execAsync(cmd);
      return `Successfully moved mouse cursor to x:${x}, y:${y}`;
    } catch (err: unknown) {
      throw new Error(`Failed to move mouse cursor: ${(err as Error).message}`);
    }
  }

  /**
   * Simulates a mouse click at current position.
   * Actions: 'left', 'right', 'double'
   */
  public static async clickMouse(action: 'left' | 'right' | 'double' = 'left'): Promise<string> {
    let dwFlags = '0x0002, 0, 0, 0, 0); $type::mouse_event(0x0004'; // left click: leftdown (0x02) + leftup (0x04)
    if (action === 'right') {
      dwFlags = '0x0008, 0, 0, 0, 0); $type::mouse_event(0x0010'; // right click: rightdown (0x08) + rightup (0x10)
    } else if (action === 'double') {
      dwFlags = '0x0002, 0, 0, 0, 0); $type::mouse_event(0x0004, 0, 0, 0, 0); $type::mouse_event(0x0002, 0, 0, 0, 0); $type::mouse_event(0x0004';
    }

    const psScript = `$sig = '[DllImport("user32.dll")] public static extern void mouse_event(int flags, int dx, int dy, int data, int extra);'; $type = Add-Type -MemberDefinition $sig -Name 'Win32Mouse' -Namespace 'Win32' -PassThru; $type::mouse_event(${dwFlags}, 0, 0, 0, 0)`;
    const cmd = `powershell -NoProfile -ExecutionPolicy Bypass -Command "${psScript}"`;

    try {
      await execAsync(cmd);
      return `Successfully performed ${action} click`;
    } catch (err: unknown) {
      throw new Error(`Failed to execute mouse click: ${(err as Error).message}`);
    }
  }

  /**
   * Types the specified text using keyboard SendKeys event.
   */
  public static async typeText(text: string): Promise<string> {
    // Escape SendKeys special characters: +, ^, %, ~, (, ), {, }
    const escaped = text
      .replace(/[{}/+^%~()]/g, '{$&}') // Wrap special characters in braces
      .replace(/'/g, "''"); // Escape PowerShell quotes

    const psScript = `Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SendKeys]::SendWait('${escaped}')`;
    const cmd = `powershell -NoProfile -ExecutionPolicy Bypass -Command "${psScript}"`;

    try {
      await execAsync(cmd);
      return `Successfully typed text: "${text.slice(0, 30)}${text.length > 30 ? '...' : ''}"`;
    } catch (err: unknown) {
      throw new Error(`Failed to send keyboard typing events: ${(err as Error).message}`);
    }
  }

  /**
   * Presses a special key, e.g. '{ENTER}', '{TAB}', '{BACKSPACE}', '{ESC}'.
   */
  public static async pressKey(key: string): Promise<string> {
    const psScript = `Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SendKeys]::SendWait('${key.replace(/'/g, "''")}')`;
    const cmd = `powershell -NoProfile -ExecutionPolicy Bypass -Command "${psScript}"`;

    try {
      await execAsync(cmd);
      return `Successfully pressed key: "${key}"`;
    } catch (err: unknown) {
      throw new Error(`Failed to press key: ${(err as Error).message}`);
    }
  }
}
